<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<base href="https://ashland.ms/"><!--[if lte IE 6]></base><![endif]-->
	<title>Page not found &raquo; Town of Ashland</title>
	<meta name="generator" content="SilverStripe - http://silverstripe.org" />
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

	<link rel="icon" type="image/png" href="themes/township/images/favicon.png">
	<link rel="stylesheet" type="text/css" href="themes/township/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/font-awesome.min.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/owl.carousel.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/Pe-icon-7-stroke.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/chosen.css" />
	<link rel="stylesheet" type="text/css" href="themes/township/css/flexslider.css" />
	
	<link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="themes/township/css/style.css">
    <link rel="stylesheet" type="text/css" href="themes/township/css/color-36c.css">
</head>
<body>
	<!-- HEADER -->
	<header class="header header-style6">
  <div class="section-main-header">
    <div class="kt-mainmenu">
      <div class="container">
        <div class="mainmenu-content">
          <div class="left-mainmenu">
            <div class="logo"> <a class="" title="TVM Logo" href="/"> <img alt="Logo" src="themes/township/images/logo6.png"> </a> </div>
          </div>
          <div class="right-mainmenu">
  <div class="kt-shopping-cart">
    <div class="icon-cart toggle-dropdown"> <i class="fa fa-gear"></i> </div>
    <div id="shopping-cart-head" class="shopping-cart-head">
      <div class="widget kt-login-register">
      	
        <form id="MemberLoginForm_LoginForm" action="/Security/LoginForm" method="post" enctype="application/x-www-form-urlencoded">
          <p id="MemberLoginForm_LoginForm_error" class="message " style="display: none"></p>
          <fieldset>
            <input type="hidden" name="AuthenticationMethod" value="MemberAuthenticator" class="hidden" id="MemberLoginForm_LoginForm_AuthenticationMethod">
            <div id="MemberLoginForm_LoginForm_Email_Holder" class="form-group">
              <label class="left" for="MemberLoginForm_LoginForm_Email">Email</label>
              <div class="middleColumn">
                <input type="text" name="Email" id="MemberLoginForm_LoginForm_Email" required="required" aria-required="true">
              </div>
            </div>
            <div id="MemberLoginForm_LoginForm_Password_Holder" class="form-group">
              <label class="left" for="MemberLoginForm_LoginForm_Password">Password</label>
              <div class="middleColumn">
                <input type="password" name="Password" class="text password" id="MemberLoginForm_LoginForm_Password" required="required" aria-required="true" autocomplete="off">
              </div>
            </div>
            <input type="hidden" name="BackURL" value="/admin/pages" class="hidden" id="MemberLoginForm_LoginForm_BackURL">
            <div class="clear"><!-- --></div>
          </fieldset>
          <div class="form-submit">
            <input type="submit" name="action_dologin" value="Log in" class="action" id="MemberLoginForm_LoginForm_action_dologin">
          </div>
        </form>
        
      </div>
    </div>
  </div>
  <!--
  <div class="kt-search-head"> <span class="togole-search"><i class="fa fa-search"></i></span>
    <div class="kt-search-box">
      <div class="overlay"></div>
      <div class="box-search-content">
        <div class="container">
          <div class="inner-search"> <span class="close-search"><i class="fa fa-close"></i></span>
            <form action="#" class="hm-form-search">
              <div class="form-search">
                <input type="text" value="" placeholder="Search">
                <span>
                <button class="button-search" name="submit_search" type="submit"><i class="fa fa-search"></i></button>
                </span> </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  -->
  <span class="togole-menu-mobile"><i class="fa fa-bars"></i></span>
  <nav class="navigation">
    <ul class="main-menu">
      
      
      <li class="menu-item"><a href='/' title='Go to the Home page'>Home</a></li>
      
      
      
      <li class="menu-item menu-parent"><a href='/about-us/' title='Go to the About Us page'>About Us <span class="caret"></span></a>
        <ul class="sub-menu">
          
          <li class="menu-item"><a href='/about-us/visitor-information/' title='Go to the Visitor Information page'>Visitor Information</a></li>
          
          <li class="menu-item"><a href='/about-us/resident-information/' title='Go to the Resident Information page'>Resident Information</a></li>
          
          <li class="menu-item"><a href='/about-us/benton-county-courthouse/' title='Go to the Benton County Courthouse page'>Benton County Courthouse</a></li>
          
          <li class="menu-item"><a href='/about-us/ashland-park/' title='Go to the Ashland Park page'>Ashland Park</a></li>
          
        </ul>
      </li>
      
      
      
      <li class="menu-item menu-parent"><a href='/reference/' title='Go to the Reference page'>Reference <span class="caret"></span></a>
        <ul class="sub-menu">
          
          <li class="menu-item"><a href='/reference/town-directory/' title='Go to the Town Directory page'>Town Directory</a></li>
          
          <li class="menu-item"><a href='/reference/plan-and-zoning/' title='Go to the Plan &amp; Zoning page'>Plan &amp; Zoning</a></li>
          
          <li class="menu-item"><a href='/reference/building-permit-policy/' title='Go to the Building Permit Policy page'>Building Permit Policy</a></li>
          
        </ul>
      </li>
      
      
      
      <li class="menu-item"><a href='/fire-department/' title='Go to the Fire Department page'>Fire Department</a></li>
      
      
      
      <li class="menu-item"><a href='/contact-us/' title='Go to the Contact Us page'>Contact Us</a></li>
      
      
    </ul>
  </nav>
</div>

        </div>
        
        
        <div class="main-container">
          <div class="ss-message">
            <div class="row">
              <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
                <div class="msg-box success"> <a href="/robots.txt#" class="msg-box-icon pe-7s-close closethis"></a> <span class="box-text"><p style="text-align: center;"><strong>THE 2019 CCR - ANNUAL WATER REPORT IS AVAILABLE UPON REQUEST </strong></p>
<p style="text-align: center;"> </p></span> </div>
              </div>
            </div>
          </div>
        </div>
        
        
      </div>
    </div>
  </div>
</header>

	<!-- /HEADER -->
	<div class="banner-page">
</div>
<div class="main-wrapper">
  <div class="container">
    <div class="main-container">
      <div class="single-blog">
        <article class="blog-item">
          <div class="post-info">
            <h3 class="title-post">Page not found</h3>
            <div class="excerpt-post"> <p>Sorry, it seems you were trying to access a page that doesn't exist.</p><p>Please check the spelling of the URL you were trying to access and try again.</p> </div>
          </div>
        </article>
        <div id="leave-comment">
          <div class="comment-form">
             </div>
        </div>
      </div>
    </div>
  </div>
</div>

    <div class="ss-client-1">
  <div class="container">
    <div class="hm-client">
    	<div class="client-item"><img src="themes/township/images/proud-host.jpg" alt=""></div>
		<div class="client-item"> <a href="http://www.dixie-net.com"><img src="themes/township/images/client-1.jpg" alt="Dixie-Net"></a> </div>
  </div>
</div>
</div>
	<footer>
  <div class="footer-top">
    <div class="link-footer">
      <div class="row">
        <div class="col-xs-12 scroll-up"> <a href="javascript:void(0)" class="scroll-bt"> <i class="pe-7s pe-7s-up-arrow"></i> <span>SCROLL UP</span> </a> </div>
      </div>
    </div>
    <div class="kt-map-ft">
      <div id="map-ft" class="kt-map"></div>
    </div>
  </div>
  <div class="widget-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
          <div class="logo-footer"> <a href="/robots.txt#"><img src="themes/township/images/logo.png" alt=""></a>
            <div class="desc-footer">Small town living, big city pride.</div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="widget widget-menu">
            <h3 class="title-widget">Quick Links</h3>
            <ul class="menu">
              
              <li><a href="/">Home</a></li>
              
              <li><a href="/about-us/">About Us</a></li>
              
              <li><a href="/reference/">Reference</a></li>
              
              <li><a href="/fire-department/">Fire Department</a></li>
              
              <li><a href="/contact-us/">Contact Us</a></li>
              
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="widget widget-menu">
            <h3 class="title-widget">Area Info</h3>
            <ul class="menu">
              <li><a href="http://www.city-data.com/city/Ashland-Mississippi.html">City-Data Page</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Ashland,_Mississippi">Wikipedia Reference</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="widget widget-contactinfo">
            <h3 class="title-widget">Contact Us</h3>
            <div class="contact-info">
              <div class="contact-text"> <i class="fa fa-map-marker"></i> <span>15870 Boundary Drive<br />Ashland, MS 38603</span> </div>
              <div class="contact-text"> <i class="fa fa-phone"></i> <span>(662) 224-6282</span> </div>
              <div class="contact-text"> <i class="fa fa-fax"></i> <span>(662) 224-8257</span> </div>
              <div class="contact-text"> <i class="fa fa-envelope"></i> <a class="mail-contact" href="mailto:ashland@dixie-net.com">ashland@dixie-net.com</a> </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bottom-footer">
    <div class="container">
      <div class="row">
        <div class="coppyright col-sm-6">
          <p>© Copyright 2020 - Town of Ashland &nbsp;|&nbsp; Design by <a href="mailto:davidharrell@mail.com">Harrell Design</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

	<script type="text/javascript" src="themes/township/js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="themes/township/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="themes/township/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="themes/township/js/jquery.debouncedresize.js"></script>
	<script type="text/javascript" src="themes/township/js/isotope.pkgd.min.js"></script>
	<script type="text/javascript" src="themes/township/js/masonry.pkgd.min.js"></script>
	<script type="text/javascript" src="themes/township/js/imagesloaded.pkgd.min.js"></script>
	<script type="text/javascript" src="themes/township/js/chosen.jquery.min.js"></script>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script type="text/javascript" src="themes/township/js/jquery.flexslider-min.js"></script>
	<script type="text/javascript" src="themes/township/js/jquery.jplayer.min.js"></script>
	<script type="text/javascript" src="themes/township/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="themes/township/js/Modernizr.js"></script>
	
	<script type="text/javascript" src="themes/township/js/hm-masonry.js"></script>
	<script type="text/javascript" src="themes/township/js/hm-map.js"></script>
	<script type="text/javascript" src="themes/township/js/custom.js"></script>
</body>
</html>