robots.txt generated by www.seoptimer.com
User-agent: *
Disallow: 
Disallow: /admin
Disallow: /aspnet-client
Disallow: /bin
Disallow: /cfeditor
Disallow: /css
Disallow: /CustomDisplays
Disallow: /CustomModules
Disallow: /fonts
Disallow: /Images
Disallow: /js
Disallow: /other
Disallow: /Special
Disallow: /styles
Disallow: /Templates
Sitemap: http://www.barnes-wi.com/sitemap.xml
