# Based on https://github.com/simonw/sfpublicworks-tree-removal-notifications/blob/main/.github/workflows/scrape.yml
name: Latest robots.txt

on:
  schedule:
    # 5 min past the hour, every 12 hours
    - cron:  '5 */12 * * *'

jobs:
  latest_metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Get latest robots.txt files
      run: python robots_txt_collector.py
    - name: Commit and push if it changed
      run: |-
        git config --global user.name "robots-bot"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Fetched at ${timestamp}" || exit 0
        git push